meta: ~

iaas_settings:
  stemcell:
    name: (( meta.stemcell-name ))
    version: (( meta.stemcell-version || "latest" ))
  compilation_cloud_properties:
    zone: (( meta.zone ))
    machine_type: (( meta.small-instance-type || "n1-standard-1" ))
  resource_pool_cloud_properties:
    - name: access_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: access_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: access_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: brain_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: brain_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: brain_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: cc_bridge_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: cc_bridge_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: cc_bridge_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: cell_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.cell-instance-type || "n1-standard-3" ))
    - name: cell_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.cell-instance-type || "n1-standard-3" ))
    - name: cell_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.cell-instance-type || "n1-standard-3" ))
    - name: colocated_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.large-instance-type || "n1-standard-3" ))
    - name: colocated_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.large-instance-type || "n1-standard-3" ))
    - name: colocated_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.large-instance-type || "n1-standard-3" ))
    - name: database_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: database_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: database_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: route_emitter_z1
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: route_emitter_z2
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: route_emitter_z3
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))
    - name: errand
      cloud_properties:
        <<: (( merge ))
        zone: (( meta.zone ))
        machine_type: (( meta.small-instance-type || "n1-standard-1" ))

  subnet_configs:
    - name: diego1
      type: manual
      subnets:
      - range: (( meta.network-0-range ))
        gateway: (( meta.network-0-gateway ))
        static: (( meta.network-0-static ))
        reserved: (( meta.network-0-reserved ))
        dns: (( meta.network-0-dns ))
        cloud_properties:
          network_name: (( meta.network-0-network-name ))
          subnetwork_name: (( meta.network-0-net-id ))
          ephemeral_external_ip: true
          tags: (( meta.network-0-security-groups ))
    - name: diego2
      type: manual
      subnets: (( merge || iaas_settings.subnet_configs.diego1.subnets ))
    - name: diego3
      type: manual
      subnets: (( merge || iaas_settings.subnet_configs.diego1.subnets ))
