meta:
  stemcell: (( merge || .meta.default_stemcell ))

  default_stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest

  resource_pools:
    small:
      cloud_properties: (( resource_pool_overrides.small_instance_type ))
    medium:
      cloud_properties: (( resource_pool_overrides.medium_instance_type ))
    large:
      cloud_properties: (( resource_pool_overrides.large_instance_type ))

resource_pool_overrides: (( merge ))

compilation:
  cloud_properties:
    ram: 1024
    disk: 8192
    cpu: 2
networks: (( merge ))

resource_pools:
  - name: small_z1
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: small_z2
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: medium_z1
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties ))

  - name: medium_z2
    cloud_properties: (( merge || meta.resource_pools.medium.cloud_properties ))

  - name: large_z1
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties ))

  - name: large_z2
    cloud_properties: (( merge || meta.resource_pools.large.cloud_properties ))

  - name: router_z1
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: router_z2
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

  - name: small_errand
    cloud_properties: (( merge || meta.resource_pools.small.cloud_properties ))

jobs:
  - name: nats_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(2, 3, 4) ))

  - name: nfs_z1
    instances: (( merge || 0 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(5, 6, 7) ))

  - name: stats_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
      
  - name: blobstore_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1

  - name: postgres_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(8) ))

  - name: router_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(9, 10, 11) ))

  - name: loggregator_z1
    instances: (( merge || 0 ))
    networks:
      - name: cf1

  - name: doppler_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1

  - name: loggregator_trafficcontroller_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1

  - name: etcd_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(12, 13, 14) ))

  - name: consul_z1
    instances: (( merge || 1 ))
    networks:
      - name: cf1
        static_ips: (( static_ips(15, 16, 17) ))
    
  - name: nats_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(2, 3, 4) ))

  - name: router_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(9, 10, 11) ))

  - name: etcd_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(12, 13, 14) ))

  - name: consul_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(15, 16, 17) ))

  - name: loggregator_z2
    instances: (( merge || 0 ))
    networks:
     - name: cf2

  - name: doppler_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2

  - name: loggregator_trafficcontroller_z2
    instances: (( merge || 0 ))
    networks:
      - name: cf2

  - name: uaa_z2
    instances: (( merge || 0 ))

  - name: api_z2
    instances: (( merge || 0 ))

  - name: api_worker_z2
    instances: (( merge || 0 ))

  - name: clock_z2
    instances: (( merge || 0 ))

properties:
  <<: (( merge ))
  logger_endpoint:
    port: 4443
  system_domain_organization: pivotal
  
  cc: (( merge ))
  
  uaa:
    clients: (( merge ))

  ccdb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: ccdb
      tag: cc
    db_scheme: postgres
    port: 5524
    roles:
    - name: ccadmin
      password: (( merge ))
      tag: admin

  uaadb:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: postgresql
    port: 5524
    roles:
    - name: uaaadmin
      password: (( merge ))
      tag: admin

  databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( merge ))
      - tag: admin
        name: uaaadmin
        password: (( merge ))
      - tag: admin
        name: diego
        password: (( merge ))
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
      - tag: diego
        name: diego
        citext: false
      - tag: diego
        name: locket
        citext: false
    collect_statement_statistics: null
    additional_config: (( merge || nil ))
